# Generated by Django 4.0 on 2024-05-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0002_alter_user_options_user_avatar_user_city_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('translation', 'Перевод'), ('invoice', 'Счет')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
    ]
